# Generated by Django 6.0.2 on 2026-02-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
