# Generated by Django 6.0.2 on 2026-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Toyota Prado', max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('latitude', models.FloatField(default=-1.286389)),
                ('longitude', models.FloatField(default=36.817223)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
